name: Flow Five Team Sk8Skins
favicon: null
layout_spectrum: 0.6422633081674576
typography_spectrum: 0.03889740421436727
title: Flow Five Team Sk8Skins
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.44729728484526277
  lightness: 0.7601560510229319
  saturation: 0.575170295778662
  rhythmicContrast: 0.43038649042136967
purpose: []
